### ISSUE TITLE
Non-webstore extensions not installed even when flag is set

### ISSUE THREAD

**Issue by NeverDecaf** [NeverDecaf/chromium-web-store#1]
If downloading a crx from non-webstore update sources, the response headers may not contain the correct mime type information in which case the .crx will be downloaded instead of installed.  
It maybe be possible to work around this by spoofing the headers or using a middle-man, perhaps chrome.webRequest could make it work.

**Comment by NeverDecaf** [comment]
webRequest cannot be used with event pages. While its possible to make background.js persistent this is not desirable. The alternative would be to use [declarativeWebRequest](https://developer.chrome.com/extensions/declarativeWebRequest) which has been in beta for at least 6 years and marked for removal at least once. Even with a persistent background page and webRequest I was still unable to get chromium to prompt to install addons by simply setting the content-type headers. Chromium likely requires either the google-specific headers (x-goog-hash, etc), a chrome web store referrer (which I did not try) or something else to prompt installation. It doesn't seem worth the overhead of having a permanent background page to add this functionality as almost every chrome app is available on the web store.

**Comment by Eloston** [comment]
If you're still interested in this, one solution in ungoogled-chromium is to relax the HTTP header requirements. We would have to look a bit more to see if this would impact browser security; e.g. from a protocol level such as other content to be misclassified as extensions, or if there is an attack that could confuse the user to installing a malicious extension.

> t doesn't seem worth the overhead of having a permanent background page to add this functionality as almost every chrome add-on is available in the web store.

It doesn't help that there is no other equally **universal and convenient** method to update extensions. Your extension provides that convenient method to install non-CWS extensions. Longer term, there could be a necessity for non-CWS extensions based on what Google is doing with Manifest V3. this is a discussion for another time and place, though.

**Comment by NeverDecaf** [comment]
> there is no other equally universal and convenient method to update extensions.

Until this changes I'm not really interested in fixing this issue. This extension is only useful and compatible with ungoogled-chromium afaik so if the need for updating non-CWS extensions increases I would rather work on implementing it directly in the browser, especially so if Google plans to make major changes with Manifest V3 (which I know next to nothing about atm.)
