### ISSUE TITLE
Chromium Web Store extension icon notification counter number is not visible properly

### ISSUE THREAD

**Issue by guest999v22** [NeverDecaf/chromium-web-store#101]
This is what the counter looked like before chrome v102 update:
![chrome old icon 01](https://user-images.githubusercontent.com/110061956/181102519-f79662f2-8e98-4ea1-883c-9508feae1356.PNG)

This is what the counter looks like in later chrome versions:
![chrome new icon 01](https://user-images.githubusercontent.com/110061956/181103131-210a8a32-4e36-4909-80c3-788436f400ca.PNG)

![chrome new icon 03](https://user-images.githubusercontent.com/110061956/181103282-003c4032-890d-4be4-a3cb-3ea585198f9a.PNG)

I have tried enabling disabling "Pervasive system accent color" chrome flag along with win 10 accent colour setting with no success. As it can be seen in the last pic, other extensions are managing it properly so it should be doable for this extension too & hopefully nothing complicated to implement.

**Comment by NeverDecaf** [comment]
Are you using version 1.5+? If so, this is caused by a bug(?) in manifest v3, see: https://support.google.com/chrome/thread/164964343/chrome-extensions-have-black-dark-box-and-text-for-notifications

**Comment by NeverDecaf** [comment]
After a quick read through https://bugs.chromium.org/p/chromium/issues/detail?id=1321962&q=badge&can=2 I believe this might be an intentional and permanent change. I think the only fix may be to change the badge background color to a color where white is more contrasting than black.

**Comment by guest999v22** [comment]
I am using v1.4.4.2. I have seen this similar issue in another extension where the developer fixed it in later version likely by doing the same thing you mentioned.

**Comment by NeverDecaf** [comment]
Yep, just had to change the red from #FF0000 to #FE0000.
