### ISSUE TITLE
Does not work with Apps it seems

### ISSUE THREAD

**Issue by wighawag** [NeverDecaf/chromium-web-store#105]
Thanks for this great extension, using it successfully for extensions

It seems to not work for apps though, see for example : https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo

Tested with chromium

**Comment by NeverDecaf** [comment]
Unfortunately, Chromium has [ended support](https://blog.chromium.org/2020/08/changes-to-chrome-app-support-timeline.html) for apps; the developer recommends installing their [desktop client](https://github.com/advanced-rest-client/arc-electron) instead. I attempted to install the app anyway in vanilla Chrome but clicking `Add to Chrome` simply prompted me to login to a google account instead.
