### ISSUE TITLE
Is there a fix yet?

### ISSUE THREAD

**Issue by Andythebrit** [NeverDecaf/chromium-web-store#106]
Sorry if this has been covered before but i am new to this without much experience......
When i used to right click this icon the red block would disappear but now a question mark is there instead.
I have read and performed the fix/s but it is still not working. Is there something i am missing?
I am attaching screen shots.
prefix Chrome shows right click Chrome1 shows left click.
![Chrome-Screenshot from 2022-10-06 08-37-37](https://user-images.githubusercontent.com/115026158/194359670-05c8cbac-5ff6-4a50-b5c5-3bf40d256ceb.png)
![Chrome1-Screenshot from 2022-10-06 08-38-27](https://user-images.githubusercontent.com/115026158/194359731-2d6e45c7-390f-46ee-b8f0-d4ae791279f1.png)

**Comment by NeverDecaf** [comment]
Can you attach the error output from `chrome://extensions/`? There should be a button labeled `Errors` that looks like this:
![image](https://user-images.githubusercontent.com/19150416/194406300-37ddea9c-15c8-4b24-a7e8-128509137740.png)
When clicked it should give you an error log. If there is no error, right click on the badge and click `Inspect popup` then check for errors in the console tab. 
More details here: https://developer.chrome.com/docs/extensions/mv3/tut_debugging/

**Comment by Andythebrit** [comment]
There is no error recorded?
October 6, 2022 12:59 PM, "NeverDecaf" ***@***.*** ***@***.******@***.***>)> wrote:
	Can you attach the error output from chrome://extensions/? There should be a button labeled Errors that looks like this:
 (https://user-images.githubusercontent.com/19150416/194406300-37ddea9c-15c8-4b24-a7e8-128509137740.png)
When clicked it should give you an error log. If there is no error, right click on the badge and click Inspect popup then check for errors in the console tab.
More details here: https://developer.chrome.com/docs/extensions/mv3/tut_debugging/ (https://developer.chrome.com/docs/extensions/mv3/tut_debugging/)

**Comment by NeverDecaf** [comment]
What version of chromium are you using? What version of the extension? If you are using 1.5+, try using 1.4.4.3, if you are using 1.4.4.3, try using 1.5.1. If there is no error output there isn't much I can do. My best guess is that one of your installed extensions is causing an issue, or you have no extensions installed, see #102
