### ISSUE TITLE
Is it possible to write a review in Chrome Web Store after extension installation?

### ISSUE THREAD

**Issue by Request-timed-out** [NeverDecaf/chromium-web-store#108]
Using ungoogled-chromium latest version, sometimes I wanna write a review after an installation in Chrome Web Store, but it doesn't think the user have installed the extension and keep saying "Add this extension to Chrome to submit a review". Is it possible to "cheat" to Chrome Store and bypass it (with google account logged-in) ?

**Comment by NeverDecaf** [comment]
I'm also interested in this since the same technique would be useful for spoofing the extension install/remove process, but this appears to be impossible.
