### ISSUE TITLE
extensions download in queue

### ISSUE THREAD

**Issue by candrapersada** [NeverDecaf/chromium-web-store#109]
will there be an option to download extensions in queue
for example after downloading and installing the extension will download and install the next extension in 1 queue?
![Download](https://user-images.githubusercontent.com/36833664/199387558-d29ce479-2026-42b0-a49c-8f929a64aeb8.PNG)

**Comment by NeverDecaf** [comment]
Could you please explain the advantage of this over the current implementation of downloading everything at once? I'm not seeing how this would be an improvement.
