### ISSUE TITLE
Grammarly is always in the list to update

### ISSUE THREAD

**Issue by kovetskiy** [NeverDecaf/chromium-web-store#11]
Hi, I have grammarly chrome extension and chromium-web-store extension always shows that it can be updated, but after update it doesn't disappear.

Here is the Grammarly extension: https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen

**Comment by NeverDecaf** [comment]
I installed Grammarly 14.947.0 and used chromium web store to update to the current version (14.951.0). The update did not seem to apply immediately so I restarted the browser and, as you described, the extension wasn't updated. However, I then tried to install the update again and this time did not close the browser afterwards. At first nothing happened but I noticed some time later (~20 minutes) that Grammarly had actually updated to the latest version.

It seems Grammarly is doing something very time intensive when updating so you may need to just leave your browser open for a while in order for the update to succeed. If that fails you can try what their support recommends and [reinstall the extension](https://support.grammarly.com/hc/en-us/articles/360018923972-Problem-updating-Grammarly-to-the-latest-version).
