### ISSUE TITLE
the mime request flag is gone

### ISSUE THREAD

**Issue by 3flowin** [NeverDecaf/chromium-web-store#111]
![chrome_jpcijdZwLK](https://user-images.githubusercontent.com/93292345/201499615-4bab3c66-f550-48cb-b3d2-4dafcf3faf2e.png)

**Comment by NeverDecaf** [comment]
The `#extension-mime-request-handling` flag is added by [ungoogled chromium](https://github.com/ungoogled-software/ungoogled-chromium/blob/master/docs/flags.md), not this extension.

**Comment by 3flowin** [comment]
even if i remove the chromium web store extension, the mime request is still not here

**Comment by NeverDecaf** [comment]
This extension does not (and can not) add or remove chrome flags, try opening an issue in the ungoogled chromium repo.
