### ISSUE TITLE
Add to Chromium install extension from crx without Drag and drop the file crx

### ISSUE THREAD

**Issue by candrapersada** [NeverDecaf/chromium-web-store#112]
add `Add to Chromium` context menu for install extension from `crx`
![chromium](https://user-images.githubusercontent.com/36833664/202874780-70d27096-68bf-4582-8097-1e55da3d12d7.PNG)

**Comment by NeverDecaf** [comment]
If you have set the `chrome://flags/#extension-mime-request-handling` flag then clicking the link should install it directly.

**Comment by candrapersada** [comment]
Chromium-based browsers like Vivaldi

**Comment by NeverDecaf** [comment]
To my knowledge this simply isn't possible without modifying your browser itself.
