### ISSUE TITLE
Can't add extensions using Ungoogled Chromium 88.0.4324.150 (macOS)

### ISSUE THREAD

**Issue by alecrobertson1** [NeverDecaf/chromium-web-store#113]
I've been able to install the Chromium Web Store extension without issue but I have no option to add any extensions from the Chrome Web Store: I see no buttons and there is no context menu item either.

<img width="1287" alt="Screenshot 2023-01-12 at 18 25 27" src="https://user-images.githubusercontent.com/4457688/212148383-8819fd5d-0f9f-4c9c-87d8-da4dc23331dd.png">

**Comment by NeverDecaf** [comment]
v1.5+ relies on Manifest V3 support and chromium version 106.0.5240.0 or higher. Try using version 1.4.4.3 of the extension instead.

**Comment by Darthagnon** [comment]
Same here; I'll try the older version, too.
