### ISSUE TITLE
Check for New Ungoogled-Chromium Binary, and ask to update. Universal Architecture Updater

### ISSUE THREAD

**Issue by karz1** [NeverDecaf/chromium-web-store#12]
[Ungoogled-Chromium](https://github.com/Eloston/ungoogled-chromium) has no auto update feature for MacOS or Linux.
This would be a great security fix to add this function to check the architecture and download the binary using this extension, or a bash script.

Or if it is easier to modify your python script that does this for windows?:
[https://github.com/NeverDecaf/ungoogled-updater](url)

**Comment by NeverDecaf** [comment]
There is already an extension for this IIRC, I think it is linked on the ungoogled-chromium wiki or perhaps on woolyss' website.

**Comment by karz1** [comment]
I looked both places, it does not exist.

**Comment by Rowisi** [comment]
linux has no update feature? There is an AUR package of Arch, PPA package for debian/ubuntu and an RPM fusion package for fedora&others.

Not sure what do you mean by that.

**Comment by NeverDecaf** [comment]
I don't plan on adding any more features to this extension. I would like to keep it as minimal as possible and will only consider feature requests that directly compliment the core functions of chromium-web-store (updating/installing extensions). woolyss does have some updaters listed [here](https://chromium.woolyss.com/#updaters) including several that claim to work with MacOS/Linux versions.
