### ISSUE TITLE
extension-mime-request-handling doesn't exist

### ISSUE THREAD

**Issue by Kxeo** [NeverDecaf/chromium-web-store#121]
Not even going to the link to the flag (chrome://flags/#extension-mime-request-handling) works! I tried checking for advanced in chrome://extensions/?options=ocaahdebbfolfmndjeplogmgcagdmblk and that ALSO wasn't there!
(Using Ungoogled-chromium on garuda)

**Comment by NeverDecaf** [comment]
My wild guess is that you built UGC without the .patch that adds the flag, but you should try opening an issue in the ungoogled chromium repo instead.
