### ISSUE TITLE
Error : Apps, extensions, and user scripts connot be added from this website

### ISSUE THREAD

**Issue by SvenMeyer** [NeverDecaf/chromium-web-store#123]
After I had problems installing the webstore kust by clicking on the release file (which worked fine for me before) and I had to install the webstore manually , see #122 , now it fails to update any other already installed extensions (in my case Metamask) and I get the error message 

`Error : Apps, extensions, and user scripts connot be added from this website`

What am I missing ?

**Comment by NeverDecaf** [comment]
Have you set the `extension-mime-request-handling` flag?
