### ISSUE TITLE
Cannot install extensions directly from the NEW chrome web store

### ISSUE THREAD

**Issue by EVANGELION-Air** [NeverDecaf/chromium-web-store#126]
It seem like we cannot install extensions directly from the NEW chrome web store: https://chromewebstore.google.com/

This link is currently in preview and will replace the existing store in the near future

**Comment by NeverDecaf** [comment]
Thanks for the warning 👍

This new web store appears to work by default with ungoogled chromium, at least on my setup it does `Version 116.0.5845.141 (Official Build, ungoogled-chromium) (64-bit)`

**Comment by NeverDecaf** [comment]
Yes, the page seems to detect my browser correctly regardless of that flag, in incognito mode I see the message `You can't add or remove items when in Incognito or Guest mode`
![image](https://github.com/NeverDecaf/chromium-web-store/assets/19150416/a26a6192-7443-47d6-b22a-32feba554926)
When not in incognito mode I see this:
![image](https://github.com/NeverDecaf/chromium-web-store/assets/19150416/25eec804-0cef-4f2b-a7fe-715007bd3745)
I tested with a fresh install of ungoogled chromium and I only see the disabled button even if I enable the flag or switch to incognito:
![image](https://github.com/NeverDecaf/chromium-web-store/assets/19150416/a80f783d-ca66-487a-8bca-607d559c2c7d)
It appears my browser is somehow exposing more information to the chrome webstore page than a fresh ungoogled chromium install. The most interesting of which is that the `window.chrome.webstorePrivate` variable is actually defined and populated in my browser while it is undefined in the fresh install.
my browser:
![image](https://github.com/NeverDecaf/chromium-web-store/assets/19150416/01e48e1b-6104-4558-ab23-6eca6d79c3d8)
fresh install:
![image](https://github.com/NeverDecaf/chromium-web-store/assets/19150416/ee9ad60c-c19a-4b39-8644-d5cc5eb787a4)
For your case specifically, I would guess that if you open the console and check `window.chrome.webstorePrivate` it will be undefined when you don't have the flag set and defined when it is set, but I have absolutely **zero** idea how or why any of this is happening. (Note that you *must* open the console on a webstore page, as `webstorePrivate` will only be defined on webstore urls.)

I don't know if any of this information is useful but it *may* be possible to manually define webstorePrivate (specifically `webstorePrivate.beginInstallWithManifest3` and `webstorePrivate.getExtensionStatus`) in an UGC install to trick the webstore into displaying the "Add to Chrome" button natively. I played around with this a bit but the "chrome check" that the store does appears to be pretty involved as spoofing the user agent and the webstorePrivate object still results in a disabled button.

**Comment by rasdmr** [comment]
Can the developer clarify? Will this extension work with the NEW chrome web store at all? Of course, now we can still choose the old version in the store settings, but I don't think Google will allow us to use the old version for a long time

**Comment by NeverDecaf** [comment]
_When_ the new store is released it will be supported by this extension.

**Comment by Secret-chest** [comment]
At least for me, the old store now redirects to the new store even though it says "Preview"
