### ISSUE TITLE
Install help please

### ISSUE THREAD

**Issue by John2003cpht** [NeverDecaf/chromium-web-store#129]
I can not seem to get it to install and work. Im running linux mint 21.2 and running the newest ungoogled chromium. I changed the flag    chrome://flags/#extension-mime-request-handling to Always prompt for install   like the instructions said. Im at a lose not sure what I need to do or what Im missing please help.

**Comment by NeverDecaf** [comment]
Did you try both alternative install methods? I can't offer much help beyond that.
