### ISSUE TITLE
Add a Install Button for Github only Browser Extensions

### ISSUE THREAD

**Issue by WiLuX-Source** [NeverDecaf/chromium-web-store#130]
Hello there, as you know many stores removing useful extensions such as FastForward etc...

I'm also an Extension developer want to know if it is possible to add a download button to a repo if a pattern is followed thank you.

**Comment by tsilvs** [comment]
Would be nice to receive extension update notifications from GitHub Releases.

**Comment by WiLuX-Source** [comment]
You need to setup your own system for that.

Firefox supports extension updates without any extra extension. In chromium you need something like chromium web store.

I'm curious about what happens in official browsers such as brave if I allow the custom extension through registry and they have a custom update url. It will probably fail(just a guess) but worth a try.
