### ISSUE TITLE
Not able to install extensions anymore, now get "Item currently unavailable. Please check the troubleshooting guide." on extension page

### ISSUE THREAD

**Issue by bacon-cheeseburger** [NeverDecaf/chromium-web-store#131]
Hi,
Whenever I try to install or update an extension, the webstore page had a big red banner that says "Item currently unavailable. Please check the troubleshooting guide."

Any ideas?

**Comment by bogdeskaa** [comment]
Uninstalling the old Chromium web store extension (1.5.3) and installing the latest version (1.5.4) fixed this issue for me.

**Comment by bacon-cheeseburger** [comment]
I installed 1.5.4 when it came out a couple months ago.

**Comment by artist-linux** [comment]
I'm using 1.5.4 and also get the purple box witth "Item currently unavailable. Please check the troubleshooting guide.".
However, the "Add to Chromium" button is colored Blue - so not greyed out - and works as normal.
This also applies to a newly created profile.

**Comment by bacon-cheeseburger** [comment]
I just tried again and the "Item current unavailable" bar is still there but the blue "Add to Chromium" is there now too. That button wasn't there when I reported this.

**Comment by LostRuins** [comment]
Google is being sneaky evil and has started A/B testing their new webstore https://chromewebstore.google.com vs https://chrome.google.com/webstore , if you are unlucky and got binned into the second option, you will no longer be able to download any extensions until you update to the newest chrome. This is part of their efforts to push manifest v3 and eventually kill off manifest v2.

For now, there is a workaround to obtain the packaged CRX using the Get CRX extension https://chromewebstore.google.com/detail/get-crx/dijpllakibenlejkbajahncialkbdkjc 

I realize some people may struggle to even obtain that CRX, so I have extracted the resource blob directly here too (it may be temporary, I do not know if it expires) : 

https://clients2.googleusercontent.com/crx/blobs/AfBom9bykW3qK6aMfDbwXj4ocTdVA1mdimUmFbctY6bVpvMR2xYRSknxv1m38O_cy72W8QNfoP8LTjFEZhaWKfbJKfX7I3XCpEscvHeRecJuMJp4fV8AxlKa5fBjcZvY9SJU0PSfN3jMgq3hmo4b/DIJPLLAKIBENLEJKBAJAHNCIALKBDKJC_1_51_0_0.crx

Dark times are ahead.

**Comment by NeverDecaf** [comment]
Just a quick reminder that even if the button isn't being replaced you should be able to right click on the web store and select "Add to Chromium" from the context menu.

**Comment by bacon-cheeseburger** [comment]
> Just a quick reminder that even if the button isn't being replaced you should be able to right click anywhere on the page and select "Add to Chromium" from the context menu.

Always the first thing I check. That wasn't available at the time of reporting.

**Comment by NeverDecaf** [comment]
You can try [1.5.4.1](https://github.com/NeverDecaf/chromium-web-store/releases/tag/v1.5.4.1) if you want more seamless integration with the new web store. This new method basically fools the store into thinking you are using a vanilla chrome browser, so functionality should be very similar to the vanilla experience.

**Comment by bacon-cheeseburger** [comment]
Just want to say that I noticed a Dark Reader update was available. With 1.5.4 there was no install option, the `unavailable` banner was there, and the blue button was to remove DR only. I updated to 1.5.4.1, the banner disappeared, and "add to Chromium" was back in the right-click menu. Thank you for the quick update @NeverDecaf !

**Comment by artist-linux** [comment]
With 1.5.4.1 sometimes the unavailable banner is present and the install button is not blue, but a simple reload fixes ths then.

**Comment by NeverDecaf** [comment]
#135 for this specific issue

**Comment by hondavideos** [comment]
> Just a quick reminder that even if the button isn't being replaced you should be able to right click anywhere on the page and select "Add to Chromium" from the context menu.

Legend, this fixed it for me. Thanks for all the work you do!

**Comment by olsonperrensen** [comment]
> Just a quick reminder that even if the button isn't being replaced you should be able to right click anywhere on the page and select "Add to Chromium" from the context menu.

Lifesaver thanks ! (also thanks to [LostRuins](https://github.com/LostRuins) for his contribution as well)

**Comment by cruzgsworks** [comment]
> Google is being sneaky evil and has started A/B testing their new webstore https://chromewebstore.google.com vs https://chrome.google.com/webstore , if you are unlucky and got binned into the new option, you will no longer be able to download any extensions until you update to the newest chrome. This is part of their efforts to push manifest v3 and eventually kill off manifest v2.
> 
> For now, there is a workaround to obtain the packaged CRX using the Get CRX extension https://chromewebstore.google.com/detail/get-crx/dijpllakibenlejkbajahncialkbdkjc
> 
> I realize some people may struggle to even obtain that CRX, so I have extracted the resource blob directly here too (it may be temporary, I do not know if it expires) :
> 
> https://clients2.googleusercontent.com/crx/blobs/AfBom9bykW3qK6aMfDbwXj4ocTdVA1mdimUmFbctY6bVpvMR2xYRSknxv1m38O_cy72W8QNfoP8LTjFEZhaWKfbJKfX7I3XCpEscvHeRecJuMJp4fV8AxlKa5fBjcZvY9SJU0PSfN3jMgq3hmo4b/DIJPLLAKIBENLEJKBAJAHNCIALKBDKJC_1_51_0_0.crx
> 
> Dark times are ahead.

Thanks a lot!

**Comment by MystesofEternity** [comment]
The methods outlined here didn't work for me and not sure about anyone else.
But here's the workaround that I ended up to:

### Workaround
1. Get this:
https://github.com/NeverDecaf/chromium-web-store/releases/
If you can't get it using the normal method, right click Chromium.Web.Store.crx then click Save link As...
Then refer to Step 4 for the roundabout way to install it.

2. Right click the extension icon -> Options
Check option to fetch .crx file

3. Go to Google Chrome Web Store and unto the page of extensions you need
Right click anywhere and click Add to Chromium

4. The .crx file is merely just a .zip file and you can forcefully unzip it using 7-Zip
or for my case in Linux, it was as easy as forcing the unzip command against the file
$ unzip my-downloaded-crx-file.crx

5. Enable Developer mode in Ungoogled Chromium     
Click Load Unpacked on the upper left
Go to the directory where you have unzipped the contents of the .crx file then click Ok
The extension should now be installed unto the browser

**Comment by comeliyeng-droid** [comment]
Hai,
Setiap kali saya mencoba memasang atau memperbarui ekstensi, halaman toko web menampilkan spanduk merah besar bertuliskan "Item saat ini tidak tersedia. Silakan periksa panduan pemecahan masalah."
