### ISSUE TITLE
i can't install the crx on uc 53.0.2785.116

### ISSUE THREAD

**Issue by KernelTech11** [NeverDecaf/chromium-web-store#132]
I'm trying to install chromium web store crx on ungoogled chromium 53.0.2785.116 with PPAPI FlashPlayer, Anyone can help me?

**Comment by WUP-P-AMAP** [comment]
HELLO ANYONE CAN HELP ME?!?

**Comment by WUP-P-AMAP** [comment]
@NeverDecaf

**Comment by NeverDecaf** [comment]
You can try version 1.4.4.3 which is the last version that supports manifest v2

**Comment by WUP-P-AMAP** [comment]
> You can try version 1.4.4.3 which is the last version that supports manifest v2
oh ok

**Comment by WUP-P-AMAP** [comment]
Nuh uh, same error
