### ISSUE TITLE
connection issue shows red question mark

### ISSUE THREAD

**Issue by markifi** [NeverDecaf/chromium-web-store#133]
could you please modify this so when it can't find an internet connection it doesn't display a red question mark on the icon? it's distracting. sure i could hide the icon entirely but it's good that it can draw attention to having an actual update to one of the extensions. my connection is unstable and the extension draws attention multiple times a day when nothing is to be updated, and it really shouldn't do in my opinion

**Comment by NeverDecaf** [comment]
If you want this behavior you can edit the file `scripts/util.js` line 346:
replace `text: "?"` with `text: ""`
