### ISSUE TITLE
can't install cws in ug 53.0.2785.116

### ISSUE THREAD

**Issue by WUP-P-AMAP** [NeverDecaf/chromium-web-store#138]
Hello! i can't install cws in 53.0.2785.116, i tried a old version and it gives the error CRX_VERSION_NUMBER_INVALID

@NeverDecaf Help me please

**Comment by WUP-P-AMAP** [comment]
@NeverDecaf shit can you help me

**Comment by NeverDecaf** [comment]
Chromium 53 predates this browser by several years. There is simply nothing I can do if your old browser doesn't support this extension.
