### ISSUE TITLE
"Add to Chrome" is disabled on https://chromewebstore.google.com

### ISSUE THREAD

**Issue by ben-page** [NeverDecaf/chromium-web-store#139]
Looks like something changed on the store again.

1. Navigate to any extension. For example, https://chromewebstore.google.com/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm
2. "Add to Chrome" is disabled. Red banner says "Item currently unavailable. Please check the troubleshooting guide."

Version 1.5.4

**Comment by ben-page** [comment]
Seems to be related to #135 

Refreshing the page as needed will fix the button.

**Comment by NeverDecaf** [comment]
Correct, this is a duplicate of 135.
