### ISSUE TITLE
Not understanding how to allow .crx install on Chromium

### ISSUE THREAD

**Issue by firefoxlover** [NeverDecaf/chromium-web-store#142]
I am using Fedora Chromium 120.0.x

I dont understand the guide, this link to the extension page does not work I just get to the main extension page. Here I find no "advanced" tab, I can just enable or disable Developer mode.

I cant even download the file on that damn browser but downloading the .crx with wget, renaming as zip and unpacking, then installing as "Developer" worked

**Comment by NeverDecaf** [comment]
It is not possible to directly install CRX files in Chromium from anywhere except the Chrome Web Store. The chromium fork `ungoogled-chromium` adds a flag which enables installing CRX files directly. What you have done (using developer mode and unpacking the CRX) is the only way to install extensions on Chromium from outside of the web store. (Unpacking may not be necessary; dropping the CRX onto the extensions page with developer mode active may work.)

The "advanced tab" is in `chromium-web-store`'s options. You won't be able to access it until you install the extension:
![image](https://github.com/NeverDecaf/chromium-web-store/assets/19150416/1df437ea-c758-4c04-9d39-5a6173af3c55)
