### ISSUE TITLE
Broken on ungoogled-chromium v121 flatpak

### ISSUE THREAD

**Issue by MANICX100** [NeverDecaf/chromium-web-store#143]
The chrome flag to always ask for installation appears to no longer work. crx just downloaded

**Comment by silentJET85** [comment]
I'm having the same issue in the portablelinux build of Ungoogled Chromium. Version 120.0.6099.224
When I have an update, it just downloads the CRX instead of installing it.

**Comment by MANICX100** [comment]
I can confirm that removing and reinstalling the extension fixes this issue for me. If you are struggling also try a fresh profile so yes it is not an issue with this extension but something that goes screwy after the flatpak update.

**Comment by silentJET85** [comment]
After some experimenting, I found what was causing the problem for me.
I had the **Custom New Tab Page** flag enabled and set to about:blank. 
If I disable the flag or change the URL to an actual website, then it works correctly. 

I notice that when it's working correctly, a new tab is opened and immediately closed whenever you click on an extension to upgrade.
With this flag enabled, that tab was staying open, and I guess that interrupts the installation prompt somehow?
