### ISSUE TITLE
New webstore all buttons greyed out for Edge and SRware Iron - is this expected?

### ISSUE THREAD

**Issue by bwims** [NeverDecaf/chromium-web-store#144]
Hello,

the new webstore has the extension buttons all greyed out for the two browsers I run - Edge and SRware Iron.  Is this to be expected?

Is a chromium version restriction?

Thanks

B.

**Comment by NeverDecaf** [comment]
I can only personally test with ungoogled chromium. If the webstore buttons aren't working you can right click and select "Add to Chromium" from the context menu.
