### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by GerryOnGithub** [NeverDecaf/chromium-web-store#15]
Package is invalid: CRX_REQUIRED_PROOF_MISSING

**Comment by nicolaasjan** [comment]
Same here.

When I click on the icon in the toolbar, the extension downloads, but when I drag it in the extensions page nothing happens...

```
environment-bootstrap-e9705d51.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
github.githubassets.com/assets/vendor-a94b745b.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
github.githubassets.com/assets/frameworks-ae021151.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
github.githubassets.com/assets/github-bootstrap-ec4bf1fd.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
```

**Comment by NeverDecaf** [comment]
Which browser, version, and extension? Also, ensure you have developer mode enabled as installing from .crx will always fail without it. As a last resort you can try `Load Unpacked` after extracting the .crx file to a folder.

**Comment by nicolaasjan** [comment]
> Which browser, version, and extension? Also, ensure you have developer mode enabled as installing from .crx will always fail without it. As a last resort you can try `Load Unpacked` after extracting the .crx file to a folder.

Browser & version: Ungoogled-Chromium 80.0.3987.149-1.bionic1
Extension: chromium-web-store 0.8.1
Developer mode is enabled.

I can't extract the crx on my system (Linux Mint 19.3; Engrampa archive manager)

**Comment by NeverDecaf** [comment]
I mistakenly thought the issue was with installing **other** extensions via chromium-web-store. I agree that the developer mode load unpacked workaround shouldn't be necessary but unfortunately Google does not. It is by design that you cannot *normally* install extensions from anywhere besides the Chrome Web Store. 
That being said, drag-and-drop installation of unsigned .crx files in dev. mode does work for me and presumably other users of ungoogled chromium, so it may be an issue with your particular build. I will leave this issue open for a while in case somebody with a similar setup can offer help.

**Comment by NeverDecaf** [comment]
see: https://github.com/Eloston/ungoogled-chromium/issues/923#issuecomment-610666060

**Comment by sasanj** [comment]
Same Here:
MacOS Catalina
Ungoogled Chromium Version 80.0.3987.163 (Official Build) (64-bit)
installed via `brew cask install eloston-chromium`
Extension: chromium-web-store 0.8.1
Developer mode is enabled.

**Comment by nxtester** [comment]
Same here:
Windows 10 Professional x64
Standard build of Eloston's ungoogled-chromium 80.0.3987.163 (722274). All patches applied apart from "Safe Browser".
Installed by Chrlauncher-win64-stable-ungoogled
Extension: chromium-web-store 0.8.1
Developer mode is enabled.

**Comment by NeverDecaf** [comment]
This appears to be a problem with ungoogled chromium, see the issue linked above. You can either use a build from [woolyss' site](https://chromium.woolyss.com/) or use the "load unpacked" [workaround](https://github.com/NeverDecaf/chromium-web-store/issues/10#issue-573495075).

**Comment by Toby4213** [comment]
Restarting the browser fixed that for me. Using ungoogled-chromium 84.0.4147.135
