### ISSUE TITLE
Error: "All extensions are up to date!" / "CWS Extensions Update Failed"

### ISSUE THREAD

**Issue by ylluminate** [NeverDecaf/chromium-web-store#152]
Just started seeing the following after updating some extensions today (restarting is not resolving the issue):
![image](https://p153.p0.n0.cdn.zight.com/items/4gu82WdY/fd74d750-3e77-4bf0-85ac-a6f720fb4a93.png?v=081ad9063de3e8944a242c0c6f063818)

I had updated three extensions, but a final one that said it needed to update had not yet been updated.

**Comment by NeverDecaf** [comment]
There should be error output in the console, right click the icon and select "inspect popup" to view it.
If there isn't anything there then check the service worker by visiting `chrome://extensions` and clicking the `Inspect views service worker` link under the extension.

**Comment by Gajus84** [comment]
Could be the newest Version of Privacy Badger that causes it (if you have it installed).

**Comment by graphixillusion** [comment]
I confirm: disabling Privacy Badger it works again. Is there any way to make an exception to make it works without disabling it?

**Comment by Gajus84** [comment]
PB had a bug fix update related to it's ability to read from the extension storage.  I'm not to deep in how chromium-web-store works but figured that this could be the reason for the CWS "fetch"-error.

`util.js:308 Error updating extension [CWS Extensions]: TypeError: Failed to fetch
    at util.js:210:25
    at new Promise (<anonymous>)
    at update_extension (util.js:209:28)
    at util.js:337:33
    at Array.map (<anonymous>)
    at util.js:336:30`

So I would wait for the PB update to land.

**Comment by NeverDecaf** [comment]
It appears that Privacy Badger is blocking the chrome update url (https://clients2.google.com/service/update2/crx) which will inevitably cause update checking to fail. I was able to "fix" this by going to Privacy Badger options => `Tracking Domains` and allowing `google.com`. This is obviously not ideal but adding `clients2.google.com` to `Disabled Sites` had no effect. (I don't use Privacy Badger myself so there may be some options I'm unaware of.)

**Comment by ghostwords** [comment]
Hello! Privacy Badger developer here. Privacy Badger for Chrome recently switched to Manifest V3 and Declarative Net Request for blocking and modifying requests. I believe this is the reason we are suddenly blocking requests that were not blocked before. If that is the case, Ungoogled Chromium (and all other Chromium forks?), have this same problem with any other extension that uses DNR to block requests and is configured to block `google.com`.

**Comment by NeverDecaf** [comment]
Thanks for stopping by! I'll leave a comment on the Privacy Badger issue with this info as I think it makes more sense to discuss this there.

**Comment by ghostwords** [comment]
OK, I just added `clients2.google.com` to Privacy Badger's workaround list of domains that should be allowed to load (although w/o access to storage). This change will take up to 24 hours to propagate to all Privacy Badgers. This should take care of the conflict between Privacy Badger and your extension, but I believe there is only a small part of a larger new problem where Declarative Net Request content blockers in Chrome can now break other extensions.

**Comment by ioc2e3** [comment]
> ... . Is there any way to make an exception to make it works without disabling it?

Same problem ...

.
