### ISSUE TITLE
Cannot install extensions in the chrome web store

### ISSUE THREAD

**Issue by bocekm** [NeverDecaf/chromium-web-store#154]
For any extension in the the chrome web store the "Add to Chrome" button is greyed out and there's a warning "Item currently unavailable. Please check the troubleshooting guide."

I use Fedora 40 with io.github.ungoogled_software.ungoogled_chromium flatpak. I have:

- changed the `chrome://flags/#extension-mime-request-handling` to `Always prompt for install`
- installed the latest [chromium-web-store](https://github.com/NeverDecaf/chromium-web-store) extension version [1.5.4.3](https://github.com/NeverDecaf/chromium-web-store/releases/tag/v1.5.4.3).

![Screenshot from 2024-08-01 13-57-01](https://github.com/user-attachments/assets/a5dea249-e91a-4a73-9966-b5311416c95c)

**Comment by galxe-lee** [comment]
me too ，please check

**Comment by NeverDecaf** [comment]
Refreshing the page may fix this. Otherwise, have you tried the context menu option (right click > Add to Chromium)?

IIRC, Chromium does not allow extensions to modify the web store so if your build of UGC doesn't patch this behavior then that could explain the issue.

**Comment by bocekm** [comment]
@NeverDecaf, the right click anywhere on the extension webpage indeed allows me to select "Add to Chromium". Thanks!
