### ISSUE TITLE
Update Check Failed

### ISSUE THREAD

**Issue by perfect7gentleman** [NeverDecaf/chromium-web-store#17]
When pressed extensions shows "Update Check Failed"
https://i.imgur.com/Yr70Qwo.png

**Comment by NeverDecaf** [comment]
You may have blocked requests to google in your firewall or elsewhere, which are unfortunately required in order to check for extension updates. Otherwise, try unchecking `Check for updates to non-web store extensions` in chromium web store's options and see if the check still fails.

**Comment by OothecaPickle** [comment]
I've also been getting this error as of late and, as you suggested, unchecking "Check for updates to non-web store extensions" fixes it, however if I keep it checked and manually select all my extensions to be ignored, the error still appears. Can you explain this? I can send a list of my installed extensions if you'd like. Thanks for any assistance you might be able to provide. :)

**Comment by NeverDecaf** [comment]
Good find @OothecaPickle, this is a legitimate bug. The code is in dire need of a rewrite anyway so I will fix this issue in the process.

**Comment by NeverDecaf** [comment]
Please let me know if you are still experiencing this in 0.9.0, and if so, it would be very helpful if you can pinpoint the exact non-webstore extension that is failing to update. (Non-webstore extensions should specify a valid "update_url" in manifest.json, or none at all. One that fails indicates either an invalid update url, or a bug in chromium web store.)

**Comment by OothecaPickle** [comment]
WIth the latest update I was able to determine that the culprit was Bypass Paywalls by checking all extensions to be ignored manually, unchecking them one by one, and checking for updates in between. Thanks!

**Comment by OothecaPickle** [comment]
and this probably isn't the place for this but the fix for bypass paywalls is to change the update_url to https://raw.githubusercontent.com/iamadamdev/bypass-paywalls-chrome/master/src/updates/updates.xml

**Comment by calvinbui** [comment]
Updating bypass-paywalls and then enabled site access on this extension fixed the problem for me

![image](https://user-images.githubusercontent.com/3604363/80305882-182b6d00-8803-11ea-8887-69723a3c868a.png)

**Comment by Rohaq** [comment]
Still having this issue when non-web store extensions is ticked - it wouldn't be so bad if the error actually let me know which extension wasn't able to update properly!

**Comment by Rohaq** [comment]
Just saw the release, updated, and it showed me what was failing to update, and it's uh, interesting.

![image](https://user-images.githubusercontent.com/246865/80632948-de02db00-8a4f-11ea-907d-c4c97f9ad7a1.png)

Which... I can only see because the extension had successfully updated? 🤔

I'm guessing that there needs to be something done to make CWS aware of its own update? 😄

**Comment by NeverDecaf** [comment]
If the update is failing you should see something like this:
![image](https://user-images.githubusercontent.com/19150416/80638815-0a5a2f80-8a2f-11ea-95bc-99a0e11695ed.png)
What you are seeing implies the update was not installed and you are still on 0.9.0. Check chrome://extensions and ensure it shows version 0.9.1 for chromium web store.

**Comment by Rohaq** [comment]
It does, but only after a full browser restart.

**Comment by NeverDecaf** [comment]
Do you no longer see any red "update failed" message?

**Comment by perfect7gentleman** [comment]
yes
https://i.imgur.com/vrI0mAH.png

**Comment by OothecaPickle** [comment]
You'll have to install the latest version of Bypass Paywalls manually for the update_url fix to be implemented.

**Comment by perfect7gentleman** [comment]
I've installed 1.7.1, the bug is still present.

**Comment by alexolog** [comment]
I am getting this on 1.4.4

![image](https://user-images.githubusercontent.com/2112513/154405289-051b297f-26b7-4ffc-8488-608e9cd772a3.png)

**Comment by NeverDecaf** [comment]
Is there any output in the console? (right click the badge => inspect popup)

**Comment by Leoniels** [comment]
I am experiencing the same issue as @alexolog with 1.4.4.2.

The console output in the inspector is `Failed to load resource: net::ERR_FILE_NOT_FOUND`

**Comment by Leoniels** [comment]
Well, after some usage, the error dissappeared. I guess it is working correctly right now.
