### ISSUE TITLE
Problem with  ungoogled chromium 80.0.3987.149 (64-Bit) windows

### ISSUE THREAD

**Issue by SIuse1** [NeverDecaf/chromium-web-store#18]
Hello,
as of late i´ve become aware of ungoogled chromium (used firefox, vivaldi before).
Downloaded the latest version (zip) of ung. chromium here: https://ungoogled-software.github.io/ungoogled-chromium-binaries/

Changed only the "handling of extension MIME type requests to "always prompt for install", everything else is as chromium started
![ungoogled chromium setup](https://user-images.githubusercontent.com/64641101/80802883-fdfde000-8bb0-11ea-8614-392f06896a23.jpg)

If i try to drag&drop your extension into the chrome://extensions window, this happens:
![ungoogled chromium extension after drag and drop](https://user-images.githubusercontent.com/64641101/80802871-f2121e00-8bb0-11ea-8a00-98a61d048cef.jpg)

nothing more.

realized this is already a problem in previous versions. So either deleted it or  merge with the pther open issue thread.

**Comment by NeverDecaf** [comment]
This is an issue with ungoogled chromium, see: https://github.com/NeverDecaf/chromium-web-store/issues/15 // https://github.com/Eloston/ungoogled-chromium/issues/923
Most seem to have good results with the `load unpacked` [workaround](https://github.com/NeverDecaf/chromium-web-store/issues/10#issue-573495075)
