### ISSUE TITLE
Can't install it

### ISSUE THREAD

**Issue by abh-oss01** [NeverDecaf/chromium-web-store#19]
The store is not getting added in the extensions menu, tried reinstalling ungoogled chromium already, and followed all the listed steps in [readme](https://github.com/NeverDecaf/chromium-web-store), in order.
Here is a video, showing what happens.

![webstore](https://user-images.githubusercontent.com/56572179/81715847-5331cf80-9496-11ea-8783-e907c9fa0be0.gif)

**Comment by NeverDecaf** [comment]
Try the workaround in #10

**Comment by abh-oss01** [comment]
I'll try, thanks
