### ISSUE TITLE
Feature Request: Update All

### ISSUE THREAD

**Issue by alivefromupstairs** [NeverDecaf/chromium-web-store#2]
Add `update all` button for two or more to-be-updated extensions in the UI or the context menu (this would be faster from a UX perspective.) But, either is fine.

**Comment by NeverDecaf** [comment]
I believe this is largely impossible due to a security feature which prevents opening multiple tabs with one user action. See [here](https://stackoverflow.com/questions/16749907/window-open-behaviour-in-chrome-tabs-windows) for more details.
It sounds like it *could* work if the user has pop-up blocking disabled, but this isn't something I want to require.

**Comment by alivefromupstairs** [comment]
Yes, I thought about it and not wanting to require popups is justified.
The problem I have with `chromium-web-store` is that updating 4 or more extensions is a chore. You could:
- consider not trying to update the list of to be updated extensions and store it if it hasn't been that long since last I opened `chromium-web-store`. (when I update an extension and proceed to the next, `chromium-web-store` displays "All extensions are up to date." and I have to wait a considerable amount of time to get to the next.)
- maybe add an update entry in the extensions' context menu that would update the single last extension, and so the process is reduced to opening the context menu and clicking update a bunch of times. 
- I don't know if this is possible, but opening update pages in the background (target="_blank" sort of behavior) and having `chromium-web-store` still opened and you can just update all extensions in a single "session". that would be a huge improvement.

**Comment by NeverDecaf** [comment]
It appears background.js is able to (inconsistently) open multiple new tabs at once. I've added an update all option to the context menu in v0.7.0.
