### ISSUE TITLE
Add locale support

### ISSUE THREAD

**Issue by TotalCaesar659** [NeverDecaf/chromium-web-store#22]
Please add locale support for translating to other languages.

**Comment by NeverDecaf** [comment]
Do you plan to work on a localization yourself? If so I've added i18n support so you should be able to test it on a "load unpacked" local version. I will also add instructions to the README for anyone who wants to help with localization.

**Comment by TotalCaesar659** [comment]
Yes, I can add message.json and test it.

**Comment by TotalCaesar659** [comment]
I've tested it and [added](https://github.com/NeverDecaf/chromium-web-store/pull/23) translation, haven't seen any bugs for a while except for [register case](https://github.com/NeverDecaf/chromium-web-store/pull/24).

**Comment by NeverDecaf** [comment]
Thank you for your help with testing and, of course, the translation :)
