### ISSUE TITLE
The latest chromium-web-store release will not prompt for install

### ISSUE THREAD

**Issue by Tank-Missile** [NeverDecaf/chromium-web-store#25]
#extension-mime-request-handling is set to "Always promt for install". The 1.0.0 release added non-webstore extension installation prompt support, but this extension will only download when I click to update it.

**Comment by NeverDecaf** [comment]
I experienced this as well. It appears that Chromium blocks access to `file:///` URLs from background scripts which breaks the workaround I was using. Strangely enough, it works if the extension was installed via `Load unpacked` which is why I never caught this before.
