### ISSUE TITLE
Installing extensions via web store

### ISSUE THREAD

**Issue by jjurkus** [NeverDecaf/chromium-web-store#30]
I tried installing ublock origin, using this build: https://github.com/macchrome/winchrome/releases/download/v84.0.4147.89-r768962-Win64/ungoogled-chromium-84.0.4147.89-2_windows.7z

I have installed chromium-web-store, and if I go to the webstore, I get a notification that the url is blocked. https://chrome.9oo91e.qjz9zk/webstore?hl=en
So, I use another url and get this error: https://www.dgip.nl/downloads/chromium-web-store-blocked.png

Now I know all those qjz9zk domains are blocked, because this is an ungoogled version. But eh, is it not working at the moment or am I doing something wrong?

**Comment by NeverDecaf** [comment]
It still works for me, do you have `chrome://flags/#extension-mime-request-handling` set to `Always prompt for install`? Having it set to default will result in the error you see.

**Comment by jjurkus** [comment]
I thought that was not needed because it already prompted for install, but I guess I was not paying enough attention.

Thank you.

**Comment by ltGuillaume** [comment]
This never worked for me (also Ungoogled-Chromium), even though I've set `chrome://flags/#extension-mime-request-handling` to `Always prompt for install`. What else can I try?
