### ISSUE TITLE
UI problem in options

### ISSUE THREAD

**Issue by wchen342** [NeverDecaf/chromium-web-store#33]
I got a UI problem when opening the options. It looks like somehow chromium cannot decide whether there should be a scroll bar. See the GIF:
![1](https://user-images.githubusercontent.com/6406743/97214750-6c67d780-17bb-11eb-9d99-4c2cb37658fc.gif)

Not sure whether it's a chromium problem or an extension problem though.

**Comment by NeverDecaf** [comment]
Does this occur regardless of where you have your cursor? Or does it only happen when you mouse over the text?

**Comment by wchen342** [comment]
No it doesn't matter where I put my cursor.

**Comment by NeverDecaf** [comment]
I believe the issue is caused by the `min-width` CSS property, let me know if this fixes it and I will update the CRX.

**Comment by wchen342** [comment]
I can confirm it firxed the problem.
