### ISSUE TITLE
Chrome Web Store search results missing buttons

### ISSUE THREAD

**Issue by NeverDecaf** [NeverDecaf/chromium-web-store#35]
The Chrome Web Store no longer shows "Add to Chrome" buttons in [search results](https://chrome.google.com/webstore/search/rss?_category=extensions). This is most likely an intended change but may be a bug considering no other part of the layout appears to have changed. Will check back in a few weeks/months time to confirm. If this is indeed intended a large chunk of code can be modified/removed in `inject.js`.

**Comment by woolyss** [comment]
Ok.
But for the rest, your extension works nicely. Latest versions of Ungoogled-chromium (frow Woolyss website) + Chrome-web-store 👍 

![The button works](https://i.imgur.com/2xQN2F0.png)
