### ISSUE TITLE
Feature suggestion: ungoogled chromium version check

### ISSUE THREAD

**Issue by michel-m** [NeverDecaf/chromium-web-store#37]
Hello,
First, thank you for your good work.
I was wondering if you'd consider also checking the browser's version (against the atom feed, for instance: https://raw.githubusercontent.com/ungoogled-software/ungoogled-chromium-binaries/master/feed.xml) within the extension itself.
In any case, thanks again!

**Comment by NeverDecaf** [comment]
This has been requested before and I understand that it would be convenient. However, I would like to keep this extension as small and streamlined as possible, which means avoiding *any* feature bloat. That being said, I might reconsider if this gets requested enough and I have some free time to work on it.

If you are simply in need of a way to keep chromium up to date there are [quite a few options](https://chromium.woolyss.com/#updaters) already.

**Comment by michel-m** [comment]
Thank you for your answer, I perfectly understand your point of view.
And thanks again for the time and effort you put into this extension.
