### ISSUE TITLE
Doesn't work!

### ISSUE THREAD

**Issue by azev** [NeverDecaf/chromium-web-store#39]
I followed all directions and installed the extension but it doesn't work.

Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by erazemk** [comment]
> I followed all directions and installed the extension but it doesn't work.
> 
> Version 87.0.4280.88 (Official Build) (64-bit)

This sort of report isn't really useful, you didn't provide any info besides then version number.
I also installed the extension yesterday in a new browser and it works just fine.

What steps did you take and what exactly doesn't work for you?
If you installed it yesterday it's very likely that there haven't been any updates to apps, is that what you meant by *doesn't work*?

The extension also doesn't help you install any new extensions, it only updates existing ones, you have to manually go to the chrome web store to get new extensions.

**Comment by NeverDecaf** [comment]
See the existing issues for help with installation, or open a new issue with a description of the problem you are having, "doesn't work" is not helpful.
