### ISSUE TITLE
backup Extension

### ISSUE THREAD

**Issue by jacob755** [NeverDecaf/chromium-web-store#43]
can we have option to make copy of current  version  Extension before update it?

**Comment by NeverDecaf** [comment]
I don't plan to add this. Making this possible would mean giving an extension access to your local filesystem which I'm not sure is even possible, but if it is it would be quite a security risk.
If you want to back up extensions you can do so [manually](https://www.bleepingcomputer.com/tutorials/how-to-view-files-installed-by-a-chrome-extension/) or you can get an old version from sites like [crx4chrome](https://www.crx4chrome.com/).

**Comment by jacob755** [comment]
thank you for explaintion understand
