### ISSUE TITLE
Offline Docs does not install

### ISSUE THREAD

**Issue by elleven11** [NeverDecaf/chromium-web-store#44]
When I try to install Offline Docs i get redirected to:
https://clients2.google.com/service/update2/crx?response=redirect&acceptformat=crx2,crx3&prodversion=87.0.4280.88&x=id%3Dadlepfefemdignonambfpicinlbppbnl%26installsource%3Dondemand%26uc

but nothing downloads. I have installed successfully various extensions, this one is the only one that gives me issues.
This is my ungoogled-chromium version:
87.0.4280.88 (Official Build) Arch Linux (64-bit)

**Comment by NeverDecaf** [comment]
This appears to be an app for Chrome OS, not an extension.

**Comment by elleven11** [comment]
Oh yes, thats right. My bad. That was the first link i found so i tought it would be that. I installed this:
https://chrome.google.com/webstore/detail/google-docs-offline/ghbmnnjooekpmoecnnnilnnbdlolhkhi
and it worked.
