### ISSUE TITLE
Translation needed for new strings

### ISSUE THREAD

**Issue by NeverDecaf** [NeverDecaf/chromium-web-store#45]
To add the feature in #41 I had to add a couple new strings:
```
"popup_removedExtensions": {
        "message": "The following extensions have been removed from the Chrome Web Store",
        "description": "Will be shown above list of removed extensions."
    },
    "popup_removedExtensionsTooltip": {
        "message": "These may have been removed due to a violation of the Terms of Service.",
        "description": "Shown when hovering over popup_removedExtensions."
    },
```
Translation is needed for these locales:
~~en~~
~~fr~~
pl
~~pt_BR~~
~~pt_PT~~
~~ru~~
Requesting help from previous contributors @TotalCaesar659 @mezysinc @kevin-ferrier @smarquespt
Thank you in advance :)

**Comment by kevin-ferrier** [comment]
Done on #46 for the french translation!

**Comment by TotalCaesar659** [comment]
Russian one is [updated](https://github.com/NeverDecaf/chromium-web-store/pull/47).

**Comment by NeverDecaf** [comment]
consolidated into #68
