### ISSUE TITLE
The extension keep promting for update

### ISSUE THREAD

**Issue by wchen342** [NeverDecaf/chromium-web-store#50]
Recently the extension keeps telling me there is an update for Ublock Origin. After I clicked the update link and installed, the red "1" doesn't disappear and it still prompts me the link. When I hover over the link it says "1.31.2 => 1.32.4", and I ckecked `chrome://extension` and uBlock Origin is actually not updated.

**Comment by NeverDecaf** [comment]
This is just how chromium handles extension updates. Extensions will not update until their background page is reloaded, which you can force by restarting your browser, you can do this quickly by visiting `chrome://restart`.

**Comment by wchen342** [comment]
Oh yes you are right. I forgot I haven't restarted chromium for some time. Closing.

**Comment by amzaf** [comment]
@NeverDecaf This is contrary to how Google Chrome extensions get installed. Why don't we need restart Chrome to get an extension updated?

**Comment by NeverDecaf** [comment]
Not sure, you'll have to ask the ungoogled chromium devs about it. All this extension does is download the crx file; what happens afterwards is up to your browser.

**Comment by NeverDecaf** [comment]
The update function is completely disabled in ungoogled chromium, the button does nothing.

**Comment by shishkin** [comment]
This is relevant to #4. Also see https://github.com/NeverDecaf/chromium-web-store/issues/4#issuecomment-1166933832 for another workaround.

**Comment by amzaf** [comment]
> This is relevant to #4. Also see [#4 (comment)](https://github.com/NeverDecaf/chromium-web-store/issues/4#issuecomment-1166933832) for another workaround.

Yes, this problem is extension specific. uBlock Origin requires browser restart but Bitwarden, for example, updates right away.

**Comment by shishkin** [comment]
> uBlock Origin requires browser restart

In my testing, I made uBlock Origin update without restarting the browser, only disabling, updating and re-enabling uBlock Origin itself.
