### ISSUE TITLE
whether there will be support for Opera Web Store and Edge Web Store

### ISSUE THREAD

**Issue by candrapersada** [NeverDecaf/chromium-web-store#55]
Can add support for Opera Web Store and Edge Web Store? for ungoogled-chromium and chromium.

**Comment by candrapersada** [comment]
and added a web shop link for easy access to the web store

**Comment by wefalltomorrow** [comment]
Also curious for such a feature.

**Comment by NeverDecaf** [comment]
I'll see what I can do, but be aware that Opera extensions do not use the `.crx` file type so the most this extension could do is let you download the `.nex` file directly. I assume you could then unzip that file and install it in chrom(ium) with "load unpacked" but it will never be as straightforward as the chrome web store with the `chrome://flags/#extension-mime-request-handling` flag set.

**Comment by NeverDecaf** [comment]
Some extra info:
Some (all?) opera extensions will download as .crx files (example: https://addons.opera.com/extensions/download/disconnect) which is actually detrimental in this situation, as chrom(ium) will try to automatically install any crx files, which will result in `'CRX_HEADER_INVALID'` errors and failure to download the file.

**Comment by NeverDecaf** [comment]
If you use the latest version of `chromium-web-store` (1.4.1) you should be able to download extensions from Opera and Edge web store. Checking for updates is not supported (and may never be, depending on whether I can find any documentation on what endpoints opera/edge use to check for extension updates.)

**Comment by NeverDecaf** [comment]
When you install an Edge or Opera extension in Chrome/Chromium, the appId assigned to it is different from the actual appId of the extension (in the corresponding store). This makes it impossible (or very difficult) to check for updates to extensions you installed from either store. Therefore, `chromium-web-store` will NOT check for updates to Edge/Opera extensions.

**Comment by Julmik647** [comment]
For Opera Addons you can use [CrossPilot](https://chromewebstore.google.com/detail/crosspilot/migomhggnppjdijnfkiimcpjgnhmnale).
