### ISSUE TITLE
CWS Stray Error About Removed Store Extensions

### ISSUE THREAD

**Issue by FluorescentGreen5** [NeverDecaf/chromium-web-store#57]
**Chromium Version:** 88.0.4324.150 (Official Build) (64-bit)
**Chromium Webstore Version:** 1.2.1

Every time I close and open Ungoogled Chromium, CWS always shows this error message:
![image](https://user-images.githubusercontent.com/37255338/107137262-03b5fc80-695f-11eb-8b27-29a768441227.png)

So far, it only seems to be occurring on one machine.

**Comment by NeverDecaf** [comment]
Does this happen after you click the ![image](https://user-images.githubusercontent.com/19150416/107160785-61017c00-6966-11eb-8e9b-4ace28bc8b4d.png) to hide the warning?

**Comment by FluorescentGreen5** [comment]
My bad, I didn't realise it was referring to uBlock Origin Extra and not uBlock Origin. Turns out gorhill removed it out of it no longer being necessary.
