### ISSUE TITLE
Translation help needed!

### ISSUE THREAD

**Issue by NeverDecaf** [NeverDecaf/chromium-web-store#60]
To add the feature requested in #53 a new string was required:
```
    "options_updateDelay": {
        "message": "Check for updates every $delayInMinutes$ minutes",
        "description": "delayInMinutes will be a field that can be edited by the user",
        "placeholders": {
            "delayInMinutes": {
                "content": "$1"
            }
        }
    },
```
Luckily, I already added this a while ago so only the oldest translations are missing it, specifically Polish and Russian.
Again, I must ask @TotalCaesar659 for your help, thank you in advance :)
Also, if anyone is willing and able to translate Polish there are more strings from #45 lacking translation.

**Comment by TotalCaesar659** [comment]
Russian translation is [updated](https://github.com/NeverDecaf/chromium-web-store/pull/61).

**Comment by NeverDecaf** [comment]
consolidated into #68
