### ISSUE TITLE
Unclear interface which extension has been removed from web store

### ISSUE THREAD

**Issue by c33s** [NeverDecaf/chromium-web-store#67]
![image](https://user-images.githubusercontent.com/649209/119257523-de739400-bbc5-11eb-86ae-feef2c4505a4.png)

the logos of the extensions are visible but obfuscated in the screenshot.

is the removed extension the one which is replaced by the warning (name still should be visible somehow) or the one above the warning or the one below the warning?

names of disabled extensions are not visible see: #66

**Comment by NeverDecaf** [comment]
Your confusion is caused by the same as #66, it looks like disabled extensions are practically invisible in dark mode. Here is what it looks like normally:
![image](https://user-images.githubusercontent.com/19150416/119262920-eb36be80-bbaa-11eb-9eb8-c897edba2259.png)
I'll try to get access to a computer that supports dark mode and test out some other colours later. Is there a standard way that greyed-out options are shown in dark mode? I don't have any experience with it so I'm not sure if there is a convention I should follow.

**Comment by c33s** [comment]
honestly the light mode doesn't make it better for me. i still don't know if the warning is for "LocalCDN" or for "Slick RSS" or replaces a plugin where the name is hidden.  (of course because you told me it replaces nothing i know this now, but from the UI i can't see it) as the text reads as "the following" i assume it's "Slick RSS". while writing this comment i think i get it, "the following" is a header and means all extensions below are not available in webstore... i assume the problem is the limited api from chome but it would be better if the red border is around all extenesions which are not available  in the store. in the current design it looks like that one extension is replaced by this message and not that the message is a header for a new section.

i don't know if there is a special standard for disabled options

you should be able to force the dark mode on all systems with a chrome flag: `chrome://flags` and search for "dark" (https://www.howtogeek.com/446198/how-to-force-dark-mode-on-every-website-in-google-chrome/) 

thank you very much for this addon <3

**Comment by NeverDecaf** [comment]
Thanks for the tip about the dark mode flag! I decided to just decrease the contrast a bit for disabled extensions, you can try the [current crx](https://github.com/NeverDecaf/chromium-web-store/blob/master/Chromium%20Web%20Store.crx) and let me know if it looks good to you.

I know I am obviously biased but I don't really see the issue with the UI; `following` implies that every item after the statement would be included, of course I'm willing to change it but I'd rather wait for more complaints to be raised before putting in the work needed (if you are reading this and were also confused by the UI please comment). Showing removed extensions isn't really the main purpose of chromium-web-store so I'm honestly fine if that part of the UI is not intuitive.

**Comment by c33s** [comment]
with 1.4.0 and your eplanation everything is readable
