### ISSUE TITLE
List of machine translated strings

### ISSUE THREAD

**Issue by NeverDecaf** [NeverDecaf/chromium-web-store#68]
#### The following strings in `messages.json` were machine translated for various reasons: (First line is the key in `messages.json`, the following lines are all the locales which were machine translated.)
`options_updateDelay`
pl
`popup_removedExtensions`
pl
pt_BR
`popup_removedExtensionsTooltip`
pl
pt_BR
`options_importExportHeading`
de
fr
pl
pt_BR
ru
`options_importExportInstallAllButton`
de
fr
pl
pt_BR
ru
`webstore_removeButton`
de
fr
it
pl
pt_BR
pt_PT
ru
zh_CN
`options_advanced`
de
es
es-419
it
no
pl
pt_BR
pt_PT
ru
tr

These are not translated at all but will be shortly:
`options_manuallyInstallTooltip`
de
es
es-419
it
no
pl
pt_BR
pt_PT
ru
tr
`options_manuallyInstall`
de
es
es-419
it
no
pl
pt_BR
pt_PT
ru
tr
`options_webstoreIntegrationTooltip`
de
es
es-419
it
no
pl
pt_BR
pt_PT
ru
tr
zh_CN
`options_webstoreIntegration`
de
es
es-419
it
no
pl
pt_BR
pt_PT
ru
tr
zh_CN

#### The following strings are not currently used anywhere in the code (so translation is not necessary):
`options_importExportDescription`
de
it
pl
pt_BR
pt_PT
ru
`notify_manuallyInstall_title`
de
es
es-419
it
no
pl
pt_BR
pt_PT
ru
tr
`notify_manuallyInstall_message`
de
es
es-419
it
no
pl
pt_BR
pt_PT
ru
tr
#### es-419 needs a quick review by a native speaker. (see #93)

**Comment by BachoSeven** [comment]
I don't think I understand what is supposed to be done; do we need to re-translate the machine-translated strings and remove the last `option_importExportDescription` from the file? (btw the latter is not even present in the italian Json atm)

**Comment by NeverDecaf** [comment]
I made this to keep track of all the strings in one place in case more are added. If the machine translation looks fine to you then you don't need to do anything.
In some cases the original translator disappeared and I was forced to machine translate new strings so having this list is helpful in case someone wants to correct the translation in the future. `options_importExportHeading` and `options_importExportInstallAllButton` are only 2 words each so I assumed machine translation would suffice, which is why I shipped v1.4.0 without asking for translation help.

#### If you want to confirm the machine translation is good let me know here and I can add a ~strikethrough~ to the list.

The unused string(s) is something I thought might be used later, you can safely ignore it as I'll open an issue if any are actually used. (For example, `options_updateDelay` was unused for months but when the option was added to the extension I already had the [translations available](https://github.com/NeverDecaf/chromium-web-store/issues/60).)

**Comment by BachoSeven** [comment]
Thanks for the explanation; both `options_importExportHeading` and `options_importExportInstallAllButton` look good to me.

**Comment by NeverDecaf** [comment]
I'm no longer maintaining this list, instead I have set the `description` of all MTL strings to `MTL` in `messages.json` so you can refer to the file for your locale to see which strings need proofreading.
