### ISSUE TITLE
Install Extensions from a List

### ISSUE THREAD

**Issue by alivefromupstairs** [NeverDecaf/chromium-web-store#7]
One can obtain a list of installed extensions for migration (from or to `ungoogled-chromiun`) from `chrome://system/`. For ease of use, could you add a place where we can dump the list and have `chromium-web-store` install it.

sample list:
```
ocaahdebbfolfmndjeplogmgcagdmblk : Chromium Web Store : version 0_8_0
cjpalhdlnbpafiamejdnhcphjbkeiagm : uBlock Origin : version 1_23_0
```
---
Also, can you consider changing this extension's name. It's very much vague and "ungooglable".  each time I have to find the issue in `ungoogled-chromium` where you referenced this extension. I can think of something along the lines of `independent-chromium-store` if not something completely novel.

**Comment by NeverDecaf** [comment]
I believe this is out of the scope of this extension and would be better suited to a separate extension or script. This extension does not actually install other extensions, it simply opens the url to the download page which can be easily done in a scripting language. Here is a python script that would do exactly that, assuming the extension list from chrome://system is in the file `ext`: 
```python
import webbrowser
chromeVersion = '79.0.3945.88'
with open('ext','r') as f:
    for l in f.readlines():
        webbrowser.open('https://clients2.google.com/service/update2/crx?response=redirect&acceptformat=crx2,crx3&prodversion={}&x=id%3D{}%26installsource%3Dondemand%26uc'.format(chromeVersion,l.split(':')[0].strip()),new=2)
```

As for the name, you make a good point and I will consider alternatives. In the meantime you can find this by searching GitHub for `chromium store` or `chromium web store`.

**Comment by alivefromupstairs** [comment]
> can be easily done in a scripting language.

Yes, I agree. One has to look up the version though, which is only one time, but I thought it would suit the extension to play that role.

> This extension does not actually install other extensions, it simply opens the url to the download page

Yeah, by install I meant interpolating the version in the url and perform what it usually does. a backup feature. But I can see why would a non-challenging task not make it as a feature.

Feel free to close the issue, unless you want to keep a reminder concerning the potential rename.
