### ISSUE TITLE
the one thing this is advertised at doing it fails to do please fix it 

### ISSUE THREAD

**Issue by suntude99** [NeverDecaf/chromium-web-store#72]
title, no you CAN'T add anything from the google web store

**Comment by IJR222** [comment]
Elaborate and properly format your bug report please. Is there an error? or an available log?

**Comment by qx-775** [comment]
Bad issues. Help us help you.

What version are you using of the extensions and browser? Have you done everything as described in the README? It should be working if you followed all the steps there.
