### ISSUE TITLE
Updating doesn't work

### ISSUE THREAD

**Issue by qx-775** [NeverDecaf/chromium-web-store#73]
Hello first off, I've been using your tool for a while now, it works amazing to install extensions! Thank you!

However, pressing the 'Update' button doesn't work and as you describe in the README it always fails to reach for updates.
There are no network requests done, and the snackbar/infobar is stuck on "Updating...".

All the chromium-web-store extensions options are correctly configured. The extensions are not set to be ignored. Automatically check for updates is selected.

So installing extensions work, I can reach the chrome webstore so nothing is blocking it on the network level.
`chrome://flags/#extension-mime-request-handling` is set to `Always prompt to install`.

What can I do? Am I missing something?

UG Version
> Version 92.0.4515.131 (Official Build, ungoogled-chromium) Arch Linux (64-bit) installed using arch linux repository on my laptop.
On my desktop it also does not work using UG from flatpak.

chromium-web-store Version
> 1.4.0

**Comment by qx-775** [comment]
Been a month, is the extension author here? :)

**Comment by NeverDecaf** [comment]
Sorry for the late reply. I am somewhat here, just missed this issue. What do you mean by automatically update? This extension doesn't have any automatic update functionality and there is also no "Update" button anywhere that I'm aware of. This extension will **check** for updates automatically but you still need to click the extension icon and manually select extensions to update them. As you discovered, `Update All` repeats this process for every extension you have.

**Comment by qx-775** [comment]
Hey thanks for answering, hope you are well.

> Edit: Are you maybe referring to the "Update" button in `chrome://extensions/`? That button is part of the browser itself and unrelated to this extension. That button does not work in any version of ungoogled chromium.

Ooooh that explains it. That makes sense.

So the extension searches for updates, but it never shows an extension which need an update. The `Install all` button at the UG extension setting is the way to update all extensions? Should it not be called 'update extensions' ? I think it will make it clearer on how to instantly update all extensions.

**Comment by NeverDecaf** [comment]
It sounds like you have the toolbar button hidden, which for some reason is now the default in chromium. You need to click the puzzle piece and then pin the extension to access the icon.
![image](https://user-images.githubusercontent.com/19150416/133675926-a747d66b-bd5b-43e9-a8e3-eec2cf080d18.png)
Once you pin it you can see how many extensions need updates (indicated by the red number). If you click the icon it will show the list of extensions that need updates; you can click any extension in this list to update it.
![](https://raw.githubusercontent.com/NeverDecaf/chromium-web-store/master/sample2.PNG)
What you have been using is the import/export feature which is only for installing a list of extensions in a new browser. If you want to update all extensions at once you can right click this icon and select `Update All Extensions`

**Comment by qx-775** [comment]
You are right! I believe I used the app the wrong way all along updating from chrome://extensions. This does indeed fix the problem. 

Kindly thank you for your support.
