### ISSUE TITLE
official chrome web store is blocked 

### ISSUE THREAD

**Issue by glocalglocal** [NeverDecaf/chromium-web-store#74]
Trying to install extensions (eg ClearURLs) from the official Chrome Web Store always results in the following error:

`Apps, extensions and user scripts cannot be added from this website`

Clicking on 'Learn more' returns a page saying: 

```
support.9oo91e.qjz9zk is blocked 
This page has been blocked by Chromium
ERR_BLOCKED_BY_CLIENT
```

I see several people report the same problem here and on Ungoogled Chromium's github. The browser's dev [says](https://github.com/Eloston/ungoogled-chromium/issues/1556) it's chromium-web-store's fault.

I am getting this with Chromium Web Store 1.4.0 and Version 92.0.4515.131 (Official Build, ungoogled-chromium) (64-bit). Also, on Windows 10.

**Comment by AgoodFriendOfSatan** [comment]
I'm having the same problem. I know that fixes keep happening, but something seems to undo it.

**Comment by NeverDecaf** [comment]
Have you set the `chrome://flags/#extension-mime-request-handling` flag to `Always prompt for install`?
