### ISSUE TITLE
Feature request: An easy way to get to the Web Store using the toolbar button

### ISSUE THREAD

**Issue by mattalexx** [NeverDecaf/chromium-web-store#78]
For some reason, Chromium and Chrome hide the Web Store link at the bottom of the collapsible left sidebar. I run Ungoogled Chromium, which doesn't have that link.

I know I could just create a bookmark, but it really just feels like I should be able to find a link to the Web Store using the "Chromium Web Store" button in my toolbar.

Just a suggestion. Thanks for creating this software.

**Comment by GreypathPro** [comment]
oK

**Comment by GreypathPro** [comment]
# SPAM POLICY

## Supported Versions

We have got versions from 3.4 till 4.1, so please check which one to use. There is no 3.5 as is was broken, so we removed it.

| Version | Supported          |
| ------- | ------------------ |
| 4.1.x   | :white_check_mark: |
| 4.0.x   | :white_check_mark: |
| 3.9.x   | :x:                |
| 3.8.x   | :white_check_mark: |
| 3.7.x   | :white_check_mark: |
| 3.6.x   | :x:                |
| 3.4.x   | :x:                |

## Reporting a issue

For reporting a issue you can:
1) Commit a file on it.
2) Report the problem to @Greypath Pro.
3) Make a pull-request.

**Comment by mattalexx** [comment]
I'm slightly confused. Did I submit the feature request incorrectly? Are you asking me to PR with the feature? Are those versions that contain the feature and my feature request is actually a bug report?

**Comment by NeverDecaf** [comment]
Looks like a mistake. Anyway, since this feature has been requested several times now I'll go ahead and add something in the manifest v3 version.

**Comment by mattalexx** [comment]
Thanks

**Comment by NeverDecaf** [comment]
Added in 1.4.3, right click the badge icon to access.
