### ISSUE TITLE
1.4.3 - New permissions

### ISSUE THREAD

**Issue by methane4** [NeverDecaf/chromium-web-store#80]
When updating to 1.4.3 i encountered some new permissions:
![Screenshot from 2021-12-09 18-54-12](https://user-images.githubusercontent.com/46012160/145458199-f06f1756-003c-4ae8-928d-8bc723f3f9f0.png)
![Screenshot from 2021-12-09 18-54-23](https://user-images.githubusercontent.com/46012160/145458207-3b194737-5f9c-49de-b3a4-d5a32fb1f2b2.png)

The first i assume it has to do with https://github.com/NeverDecaf/chromium-web-store/issues/55, however what about "Manage your downloads" and "Manage your apps, extensions, and themes"?

**Comment by NeverDecaf** [comment]
As you say, the new website permissions are required to run scripts on the Opera and Edge addon websites. As for the other permissions, those were already required in previous versions of chromium-web-store, I guess the prompt is just showing all permissions regardless of whether you granted them in the past or not.

**Comment by methane4** [comment]
> As you say, the new website permissions are required to run scripts on the Opera and Edge addon websites. As for the other permissions, those were already required in previous versions of chromium-web-store, I guess the prompt is just showing all permissions regardless of whether you granted them in the past or not.

Okay, thank you
