### ISSUE TITLE
PDF Plugin Name must be set to Google Chrome?

### ISSUE THREAD

**Issue by indecisiveuser** [NeverDecaf/chromium-web-store#81]
Hello, I installed

Chromium 96.0.4664.110 (Official Build, ungoogled-chromium) (x86_64)
Chromium Web Store v. 1.4.3

chrome://flags/#extension-mime-request-handling is set to Always prompt for install, and https://chrome.google.com/* and https://clients2.google.com/* are allowed. No other extensions are installed.

However, the "Add to Chromium" button did not appear on the Chrome Web Store until I set the internal PDF plugin name to Google Chrome. Is this something we should add to the readme?

**Comment by NeverDecaf** [comment]
Are you sure the problem isn't caused by something else? This issue hasn't been reported before and my instance works fine regardless of PDF plugin name.

**Comment by indecisiveuser** [comment]
You're probably right—now that I try to replicate the issue, changing the PDF plugin name doesn't have any effect. It seems to be working just fine now :) Thank you for this extension!
