### ISSUE TITLE
Can't update extensions since 1.4.4

### ISSUE THREAD

**Issue by leonardo73-max** [NeverDecaf/chromium-web-store#84]
Since the change in 1.4.4 https://github.com/NeverDecaf/chromium-web-store/issues/83
I can't update my extensions anymore. I simply clicked "Add to Chromium" from the Chrome Web Store and the new version would overwrite the old one. Since there is "Remove from Chromium" I can't do that anymore, so I have to remove the extension and install it again losing all related data

**Comment by NeverDecaf** [comment]
The intended way to update extensions is via the chromium-web-store badge, does this method not work for you?
(Left click on the extension you want to update)
![image](https://user-images.githubusercontent.com/19150416/153767130-cbc8bf06-0cac-4812-a370-60d6dc1df256.png)
If not, you can right click on the Chrome Web Store page and select "Add to Chromium" from the context menu.
