### ISSUE TITLE
Can't update through the icon

### ISSUE THREAD

**Issue by ENTERspaceAspaceUSERNAME** [NeverDecaf/chromium-web-store#86]
I am getting "Package is invalid: 'CRX_REQUIRED_PROOF_MISSING'.". The file gets removed automatically.
![image](https://user-images.githubusercontent.com/98239309/154767232-b4142e00-1f61-4e96-a19d-a584904f6930.png)

**Comment by ENTERspaceAspaceUSERNAME** [comment]
I have not changed any flags. They're all on default.

**Comment by ENTERspaceAspaceUSERNAME** [comment]
I have just checked, it's at default.

**Comment by ENTERspaceAspaceUSERNAME** [comment]
Okay, it tells me to add the extension, I add it. I still have the red thing and when I click on the icon, it still shows that it needs an update. I have a .crx file while the prompt is showing, so if I want to add it through the .crx file, it shows that the file has been deleted or changed. And I'm on a different PC. It only seems to update and the .crx file is only present when I download it via Github.

**Comment by dkleehammer** [comment]
I'm having this issue, I have set the flags and I still have the red icon telling me chrome web store needs to be updated.
