### ISSUE TITLE
How to correctly update Chromium Web Store?

### ISSUE THREAD

**Issue by fastcat001** [NeverDecaf/chromium-web-store#88]
First, thanks for creating such an amazing extension.

Not an issue, but I've a question about correct way of updating Chromium Web Store.

So when you release a new Chromium Web Store .crx file, I've to remove the previous Chrome Web Store from the extensions, and I've just to copy the new one?

Will the new webstore .crx file still detect the other extensions installed using the previous Chromium Web Store build?

Thanks

**Comment by NeverDecaf** [comment]
You don't need to uninstall the previous version before installing the latest one.

**Comment by fastcat001** [comment]
Dear @NeverDecaf , thanks for your response and I'm forever thankful to you for developing this lifesaving extension.
