### ISSUE TITLE
Won't install on ungoogled-chromium 79.0.3945.130 

### ISSUE THREAD

**Issue by Gooberpatrol66** [NeverDecaf/chromium-web-store#9]
I download the .crx, drag it into the "drop to install", and the page freezes.

**Comment by albertoventurini** [comment]
I had the same issue on ungoogled-chromium 80.0.3987.106. I solved it by downloading the extension source code, heading over to chrome://extensions, ensuring that developer mode is enabled, clicking on "load unpacked" and selecting the src folder of the extension source code. Hope that helps.

**Comment by NeverDecaf** [comment]
Created a new issue for this problem as it has been reported several times (#10)
