### ISSUE TITLE
Can't update uBlock Origin extension

### ISSUE THREAD

**Issue by leonardo73-max** [NeverDecaf/chromium-web-store#91]
I can't find a way to update uBlock Origin without first uninstalling it and lose all settings.

It's the only extension I can't update, I try to update it like usual, but after clicking "add extension" nothing happens. I have this issue since the beginning. Is there some limitation on it?

Thanks!

**Comment by NeverDecaf** [comment]
Some extensions won't update until you restart your browser #4

**Comment by NeverDecaf** [comment]
Feel free to re-open this issue if restarting your browser doesn't fix the problem.
