### ISSUE TITLE
Version Number Bug

### ISSUE THREAD

**Issue by bkrucarci** [NeverDecaf/chromium-web-store#96]
Please check the version number. Thanks.

> That's because the `update_url` referenced in said extension's manifest still states 1.4.4.1 as latest version:
> 
> https://raw.githubusercontent.com/NeverDecaf/chromium-web-store/master/updates.xml
> 
> With this version scheme it would be easy to determine whether it's actually new or not. But it's impossible to reliably derive version order from _all_ the different schemes out there (some just use hashes). So to keep it simple, a version is always reported as new when it's different.
> 
> TLDR; It's not a bug, it's just that the author of Chrome Web Store needs to update their repo.

_Originally posted by @kkkrist in https://github.com/kkkrist/chromium-notifier/issues/46#issuecomment-1140404089_

**Comment by NeverDecaf** [comment]
I intentionally left `updates.xml` outdated as patch versions only contain a new language/translation and I didn't want to prompt all users for an update since the change won't affect most of them. I'll be bumping the version to 1.5 soon™ which will fix this issue.

**Comment by bkrucarci** [comment]
> I intentionally left `updates.xml` outdated as patch versions only contain a new language/translation and I didn't want to prompt all users for an update since the change won't affect most of them. I'll be bumping the version to 1.5 soon™ which will fix this issue.

Thanks! Waiting for the new release.

**Comment by NeverDecaf** [comment]
Manifest v3 is more broken and incomplete than I could ever have imagined, so it may be a while until I update `updates.xml`. If you want to fix this temporarily then you can edit `manifest.json` and change the version number to the exact version specified in `updates.xml`.

However, that should not be necessary as the version scheme *is* strictly specified and enforced: [https://developer.chrome.com/docs/extensions/mv2/manifest/version/](https://developer.chrome.com/docs/extensions/mv3/manifest/version/). If you try to use an invalid version number, for example a hash, chromium will simply refuse to install your extension.
![image](https://user-images.githubusercontent.com/19150416/176989680-df59b770-4961-4359-bb09-44bda3915cee.png)
