### ISSUE TITLE
Duplicate Extensions Between Profiles?

### ISSUE THREAD

**Issue by dm17** [NeverDecaf/chromium-web-store#99]
What's the recommended method to dupilcate your installed & configured extensions to new profiles, as you make them?

**Comment by NeverDecaf** [comment]
I believe you can just copy the contents of the extensions directory from one profile to another. This isn't really within the scope of this project but I'll leave this open in case somebody else chimes in with a better method.

**Comment by dm17** [comment]
Thanks - good to have a place for such discussions as this wouldn't be entertained as a primary method in regular chromium.
